/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LaunchOptions {
  maxBrowsers?: number
}
export declare function chromium(): Chromium
export declare class Browser {
  newPage(): Promise<Page>
  close(): Promise<void>
}
export declare class Page {
  goto(url: string): Promise<void>
  title(): Promise<string>
  content(): Promise<string>
  click(selector: string): Promise<void>
  fill(selector: string, value: string): Promise<void>
  evaluate(expression: string): Promise<any>
  screenshot(): Promise<Buffer>
  waitForSelector(selector: string): Promise<void>
  close(): Promise<void>
}
export declare class Chromium {
  static launch(options?: LaunchOptions | undefined | null): Promise<Browser>
}
