/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface GetByTextOptions {
  /** Default false: case-insensitive substring. */
  exact?: boolean
}
export interface GetByRoleOptions {
  /** Accessible name. Default: case-insensitive substring. */
  name?: string
  exact?: boolean
}
export interface LaunchOptions {
  maxBrowsers?: number
  /** Browser binary. Default: chrome-headless-shell when headless and installed, else Chrome. */
  executablePath?: string
  /** Default true. */
  headless?: boolean
}
export interface ProxyOptions {
  /** `http://host:port`, `socks5://host:port`, ... */
  server: string
  /** Comma-separated hosts that skip the proxy. */
  bypass?: string
  username?: string
  password?: string
}
export interface NewPageOptions {
  proxy?: ProxyOptions
}
export interface GotoOptions {
  /** Default "load". */
  waitUntil?: 'load' | 'domcontentloaded' | 'networkidle' | 'commit'
}
export interface ScreenshotOptions {
  fullPage?: boolean
}
export interface ViewportSize {
  width: number
  height: number
}
export declare function chromium(): Chromium
export declare class Browser {
  /** A fresh browser context. `proxy` applies to this page only. */
  newPage(options?: NewPageOptions | undefined | null): Promise<Page>
  close(): Promise<void>
}
export declare class Page {
  goto(url: string, options?: GotoOptions | undefined | null): Promise<void>
  title(): Promise<string>
  content(): Promise<string>
  click(selector: string): Promise<void>
  fill(selector: string, value: string): Promise<void>
  evaluate(expression: string): Promise<any>
  screenshot(options?: ScreenshotOptions | undefined | null): Promise<Buffer>
  setViewportSize(size: ViewportSize): Promise<void>
  waitForSelector(selector: string): Promise<void>
  /** CSS, `text=`, or `role=` selector. */
  locator(selector: string): Locator
  getByText(text: string, options?: GetByTextOptions | undefined | null): Locator
  getByRole(role: string, options?: GetByRoleOptions | undefined | null): Locator
  frameLocator(selector: string): FrameLocator
  close(): Promise<void>
}
/** Lazy, like Playwright's: every action runs the query again. */
export declare class Locator {
  click(): Promise<void>
  fill(value: string): Promise<void>
  /** Waits until visible. */
  waitFor(): Promise<void>
  textContent(): Promise<string | null>
}
/** An iframe, same- or cross-origin, to find elements in. */
export declare class FrameLocator {
  locator(selector: string): Locator
  getByText(text: string, options?: GetByTextOptions | undefined | null): Locator
  getByRole(role: string, options?: GetByRoleOptions | undefined | null): Locator
  /** A nested iframe inside this one. */
  frameLocator(selector: string): FrameLocator
}
export declare class Chromium {
  static launch(options?: LaunchOptions | undefined | null): Promise<Browser>
}
