/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface GetByTextOptions {
  /** Default false: case-insensitive substring. */
  exact?: boolean
}
export interface GetByRoleOptions {
  /** Accessible name. Default: case-insensitive substring. */
  name?: string
  exact?: boolean
}
export interface LaunchOptions {
  maxBrowsers?: number
  /** Browser binary. Default: chrome-headless-shell when headless and installed, else Chrome. */
  executablePath?: string
  /** Default true. */
  headless?: boolean
}
export interface ProxyOptions {
  /** `http://host:port`, `socks5://host:port`, ... */
  server: string
  /** Comma-separated hosts that skip the proxy. */
  bypass?: string
  username?: string
  password?: string
}
/** Playwright's `newContext` options that Fluxwright supports. */
export interface NewPageOptions {
  proxy?: ProxyOptions
  userAgent?: string
  /** BCP 47, e.g. `de-DE`: `navigator.language`, `Accept-Language` and `Intl`. */
  locale?: string
  /** IANA, e.g. `Asia/Tokyo`. */
  timezoneId?: string
  /** Also needs `permissions: ['geolocation']`, as in Playwright. */
  geolocation?: Geolocation
  /** `geolocation`, `notifications`, `clipboard-read`, ... granted to every origin. */
  permissions?: Array<string>
  viewport?: ViewportSize
  deviceScaleFactor?: number
  colorScheme?: 'light' | 'dark' | 'no-preference'
  /**
   * Cookies and localStorage to start from: what `page.storageState()` returned, or the
   * path of the JSON file it saved.
   */
  storageState?: StorageState | string
}
export interface Geolocation {
  latitude: number
  longitude: number
  /** Meters. Default 0. */
  accuracy?: number
}
/** Cookies and localStorage, in Playwright's `storageState` format: files work in both. */
export interface StorageState {
  cookies: Array<Cookie>
  origins: Array<OriginStorage>
}
export interface Cookie {
  name: string
  value: string
  domain: string
  path: string
  /** Unix seconds; -1 for a session cookie. */
  expires: number
  httpOnly: boolean
  secure: boolean
  sameSite: 'Strict' | 'Lax' | 'None'
}
export interface OriginStorage {
  origin: string
  localStorage: Array<StorageItem>
}
export interface StorageItem {
  name: string
  value: string
}
export interface GotoOptions {
  /** Default "load". */
  waitUntil?: 'load' | 'domcontentloaded' | 'networkidle' | 'commit'
}
export interface ScreenshotOptions {
  fullPage?: boolean
}
export interface ViewportSize {
  width: number
  height: number
}
export declare function chromium(): Chromium
export declare class Browser {
  /** A fresh browser context. Every option applies to this page only. */
  newPage(options?: NewPageOptions | undefined | null): Promise<Page>
  close(): Promise<void>
}
export declare class Page {
  /**
   * Every cookie in this page's context, plus localStorage of the current origin. Pass it
   * (or a file it was saved to) as `newPage({ storageState })` to skip logging in again.
   */
  storageState(): Promise<StorageState>
  goto(url: string, options?: GotoOptions | undefined | null): Promise<void>
  title(): Promise<string>
  content(): Promise<string>
  click(selector: string): Promise<void>
  fill(selector: string, value: string): Promise<void>
  evaluate(expression: string): Promise<any>
  screenshot(options?: ScreenshotOptions | undefined | null): Promise<Buffer>
  setViewportSize(size: ViewportSize): Promise<void>
  waitForSelector(selector: string): Promise<void>
  /** CSS, `text=`, or `role=` selector. */
  locator(selector: string): Locator
  getByText(text: string, options?: GetByTextOptions | undefined | null): Locator
  getByRole(role: string, options?: GetByRoleOptions | undefined | null): Locator
  frameLocator(selector: string): FrameLocator
  close(): Promise<void>
}
/** Lazy, like Playwright's: every action runs the query again. */
export declare class Locator {
  click(): Promise<void>
  fill(value: string): Promise<void>
  /** Waits until visible. */
  waitFor(): Promise<void>
  textContent(): Promise<string | null>
}
/** An iframe, same- or cross-origin, to find elements in. */
export declare class FrameLocator {
  locator(selector: string): Locator
  getByText(text: string, options?: GetByTextOptions | undefined | null): Locator
  getByRole(role: string, options?: GetByRoleOptions | undefined | null): Locator
  /** A nested iframe inside this one. */
  frameLocator(selector: string): FrameLocator
}
export declare class Chromium {
  static launch(options?: LaunchOptions | undefined | null): Promise<Browser>
}
